language: node_js
node_js: node
cache: yarn
install:
  - yarn install
  - cd ./client
  - yarn install
  - cd ..
script:
  - cd ./client
  - yarn test
  - cd ..
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simple-e-shop
  on:
    repo: f0ll0wthewhiterabbit/simple-eshop
