export const STORAGE_FIELD_TOKEN = 'token'
export const STORE_FIELD_PRODUCTS = 'products'
export const STORE_FIELD_USERS = 'users'
export const STORE_FIELD_CURRENT_USER = 'usersCurrent'
export const URL_FIELD_RATINGS_FILTER = 'myRatings'
export const URL_FIELD_NO_FILTER = 'all'
