export const MAIN_PAGE_PATH = '/'
export const SING_IN_PAGE_PATH = '/sign-in'
export const SING_UP_PAGE_PATH = '/sign-up'
export const ADMIN_PAGE_PATH = '/admin'
export const ADMIN_USERS_PAGE_PATH = '/admin/users'
export const ADMIN_PRODUCTS_PAGE_PATH = '/admin/products'
export const ADMIN_PRODUCT_ADD_PAGE_PATH = '/admin/products/add'
export const ERROR_PAGE_PATH = '/error'
